apiVersion: v1
kind: Service
metadata:
  name: {{ include "speech-diarization.fullname" . }}
  labels:
    {{- include "speech-diarization.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8501
      protocol: TCP
      name: http
  selector:
    {{- include "speech-diarization.selectorLabels" . | nindent 4 }}
