apiVersion: v1
kind: Service
metadata:
  name: speech-ai-service
  labels:
    app: speech-ai
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8501
      protocol: TCP
      name: http-streamlit
  selector:
    app: speech-ai
