{{- if .Values.ezua.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "voice-agent.fullname" . }}
  labels:
    {{- include "voice-agent.labels" . | nindent 4 }}
spec:
  hosts:
    - {{ .Values.ezua.virtualService.endpoint | quote }}
  gateways:
    - {{ .Values.ezua.virtualService.istioGateway }}
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ include "voice-agent.fullname" . }}
            port:
              number: {{ .Values.service.port }}
      timeout: 300s
{{- end }}
